---
  environment: production
  address: 127.0.0.1
  port: 3000
  pid: log/thin.pid
  rackup: conf/thin.ru
  log: log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 1024
  daemonize: true
